### ISSUE TITLE
Broken documentation links to old docs site

### ISSUE THREAD

**Issue by Griffin-Sullivan** [pulp/pulp_python#406]
The following pages have links to the old readthedocs.org documentation that no longer exists. They need to be updated with the link to the https://docs.pulpproject.org/pulp_python/.

1. https://github.com/pulp/pulp_python README
2. https://pulpproject.org/content-plugins/ Python plugin under Pulp 3 Content Plugins Information table
3. https://pulpproject.org/2021/01/13/pulp-python-3.0-release/

**Comment by melcorr** [comment]
>     2. https://pulpproject.org/content-plugins/ Python plugin under Pulp 3 Content Plugins Information table
> 
>     3. https://pulpproject.org/2021/01/13/pulp-python-3.0-release/

https://github.com/pulp/pulpproject.org/pull/383

Thanks!
