### ISSUE TITLE
base_url and reverse proxy, LB or else

### ISSUE THREAD

**Issue by micheelengronne** [pulp/pulp_python#412]
With pulpcore and other plugins we can set `CONTENT_ORIGIN` and `CONTENT_PATH_PREFIX` that make possible to use the base_url in a complex environment where the local fqdn is not reachable from outside.

Is it possible to alter the current base_url in the python plugin according to these parameters ?

**Comment by gerrod3** [comment]
With pulp_python 3.4.0 the `PyPI` endpoints "moved" from the Pulp content app to the Pulp API. So before if you had a distribution named 'foo', `CONTENT_ORIGIN` of 'http://pulp-content.com' and `CONTENT_PATH_PREFIX` of '/pulp/content/', then you could access the simple api at 'http://pulp-content.com/pulp/content/foo/simple/'.  Now if your Pulp API is available at 'http://pulp-api.com'  you access the simple api at 'http://pulp-api.com/pypi/foo/simple' . 

**Note** the old location is still available and behind the scenes the actual download links will redirect there.

**Comment by micheelengronne** [comment]
My question is, how can I alter the base_url to correspond to the host and port I access with ? I have pulp_python in a custom container image named as `pulp_python`, it gives the following url https://pulp_python/pypi. But I reach this API from another host and port via port forwarding, I reach it from `https://localhost:9002/api/v3`. How can I alter the base_url to give this API address instead ?

**Comment by gerrod3** [comment]
I understand your problem now. Currently there is no way to set the `base_url` to another host and port for the pulp_python plugin, but I can add a new setting similar to `CONTENT_ORIGIN` to allow for setting the `base_url` to your desired address for the next release.

**Comment by micheelengronne** [comment]
Thanks a lot !
