### ISSUE TITLE
pulp to pulp syncs fail with  405 on /pypi

### ISSUE THREAD

**Issue by jlsherrill** [pulp/pulp_python#462]
Trying to sync one pulp server from another (or even one remote from another on the same instance), results in a 405 when accessing /pypi

"POST /pulp/content/Default_Organization/Library/custom/python/python2/pypi HTTP/1.1" 405 226 "-" "bandersnatch 4.4.0 aiohttp XML-RPC client 

The sync doesn't error, but no content is synced

**Comment by gerrod3** [comment]
Pulp to Pulp sync is still in tech preview and currently you can't fully sync from another Pulp instance without specifying the includes list. Behind the scenes Bandersnatch uses xlmrpc calls to get the full package list from the remote (typically PyPI), but we don't support the xlmrpc endpoints currently. I haven't looked into how difficult it would be to actually support them, but there are other options like parsing the simple pages for packages present. Here is the note about the current implementation: https://github.com/pulp/pulp_python/blob/47f22a313afa6616b6a21432f31ba148ebff5884/pulp_python/app/tasks/sync.py#L191-L195
