### ISSUE TITLE
duplicate operationId in generated openapi spec

### ISSUE THREAD

**Issue by jlsherrill** [pulp/pulp_python#594]
**Version**
3.8.0

**Describe the bug**
in the generated openapi spec, there seems to be a duplicated operationId:

```
        "/pypi/{path}/simple/": {
            "get": {
                "operationId": "pypi_simple_read",
```
```
        "/pypi/{path}/simple/{package}/": {
            "get": {
                "operationId": "pypi_simple_read",
```

I don't think this is allowed and i'm seeing some go bindings generation generating bad code due to it.

**Comment by mdellweg** [comment]
Too bad this is not found by the api validator:
https://github.com/pulp/pulp_python/blob/main/template_config.yml#L14
